export const LANGUAGES = ['es', 'en'] as const;
export type Language = (typeof LANGUAGES)[number];

export const copy = {
  es: {
    investorModelView: {
      headerTitle: "Modelo de inversión",
      heroSubtitle: "Supuestos y rendimientos estimados",
      heroNote: "Ajusta las variables para ver el impacto en tiempo real.",
      monthPositive: (month: number) => `Mes ${month}`,
      keyStats: {
        closings: "Cierres Y1",
        commissionRevenue: "Ingreso comisión Y1",
        netIncome: "Utilidad neta Y1",
        cashMonth: "Mes de caja positiva",
        asp: "ASP",
        capture: "Captura",
        closeAndCpl: "Cierre / CPL",
        salaries: "Nómina Y1",
      },
      metricsGlossary: [
        "GMV: Valor bruto de mercancía",
        "CPL: Costo por lead",
        "ASP: Precio promedio por cierre",
      ],
      glossaryTitle: "Glosario",
      glossaryItems: [
        "GMV: Valor de propiedades transaccionadas",
        "Capture: Porcentaje de comisión retenida",
        "ASP: Precio promedio por propiedad",
      ],
      howToReadTitle: "Cómo leer",
      howToReadPoints: [
        "Modifica los controles para recalcular las tablas.",
        "Las tablas muestran los resultados con los supuestos actuales.",
        "Puedes restablecer los valores con el botón Reset.",
      ],
      howToReadDisclaimer: "Montos expresados en USD.",
      controlsTitle: "Controles",
      controlsRealtimeNote: "Los cambios se reflejan en tiempo real.",
      resetButton: "Reset",
      controlGroups: {
        commercial: {
          title: "Supuestos comerciales",
          aspLabel: "ASP (USD)",
          aspHelp: "Precio promedio por cierre.",
          captureLabel: "% Captura",
          captureHelp: "Porcentaje de comisión que retiene TAO.",
          closeRateLabel: "% Cierre",
          closeRateHelp: "Porcentaje de leads que convierten en venta.",
          cplLabel: "CPL (USD)",
          cplHelp: "Costo por lead generado.",
          closingsGroupTitle: "Cierres / GMV",
          closingLabelY1: "Cierres Y1",
          closingLabelY2: "Cierres Y2",
          closingLabelY3: "Cierres Y3",
          closingHelpY1: "GMV Y1 estimado: {gmv} con el ASP actual.",
          closingHelpY2: "GMV Y2 estimado: {gmv} con el ASP actual.",
          closingHelpY3: "GMV Y3 estimado: {gmv} con el ASP actual.",
        },
        team: {
          title: "Equipo",
          intro: "Configura sueldos y contrataciones por año.",
          srTitle: "AI Sr Analyst",
          jrTitle: "AI Jr Analyst",
          salaryLabel: "Sueldo mensual (USD)",
          salaryHelpSr: "Sueldos de analistas senior (contrataciones escalonadas).",
          salaryHelpJr: "Sueldos de analistas junior (contrataciones escalonadas).",
          countLabel: "Contrataciones",
          srCountHelp: "Cantidad de hires senior distribuidos por año.",
          jrCountHelp: "Cantidad de hires junior distribuidos por año.",
          yearLabel: "Año",
        },
        brainium: {
          title: "Brainium",
          monthlyLabel: "Fee mensual Brainium ({months} meses)",
          monthlyHelp: "Monto fijo mensual durante los primeros meses.",
          successLabel: "Success fee",
          successHelp: "Monto a pagar contra éxito.",
          revshareLabel: "% Revshare",
          revshareHelp: "Porcentaje de revenue compartido.",
          totalsHelp: "Total por año: Y1 {y1}, Y2 {y2}, Y3 {y3}.",
        },
      },
      sectionTitles: {
        teamDashboard: "Dashboard de equipo",
        unitEconomics: "Unit economics",
        pnl: "P&L",
        sensitivity: "Sensibilidad",
        cash: "Caja",
      },
      teamTableHeaders: ["Rol", "Salario mensual", "Contratación"],
      teamTableEmpty: "Agrega contrataciones para ver el costo por año.",
      unitEconomicsRows: {
        commission: "Comisión por cierre",
        acquisition: "Adquisición por cierre",
        contribution: "Contribución por cierre",
      },
      pnlHeaders: [
        "Año",
        "Cierres",
        "GMV",
        "Leads",
        "Media",
        "Ingreso comisión",
        "% Broker",
        "Nómina",
        "Overhead",
        "Utilidad neta",
        "Margen neto",
      ],
      sensitivityHeaders: [
        "Escenario",
        "Cierres",
        "% Captura",
        "% Cierre / CPL",
        "GMV",
        "Leads / Media",
        "Ingreso comisión",
        "% Broker",
        "Nómina + OH",
        "Utilidad neta",
        "Margen neto",
      ],
      cashChartTitle: "Flujo de caja Y1",
      cashSummaryTitle: "Resumen de caja",
      cashSummary: {
        burn: "Burn mensual pre-ventas:",
        net: "Ingreso neto mensual post-ventas:",
        deficit: "Déficit máximo:",
        turn: "Mes de cruce a positivo:",
      },
    },
    investorNarrativeView: {
      title: 'Narrativa de inversión',
      intro: 'Explicación del modelo de inversión de TAO.',
      // agrega más claves aquí después, si hace falta
    },
  },
  en: {
    investorModelView: {
      headerTitle: "Investment model",
      heroSubtitle: "Assumptions and estimated returns",
      heroNote: "Tweak the inputs to see the real-time impact.",
      monthPositive: (month: number) => `Month ${month}`,
      keyStats: {
        closings: "Closings Y1",
        commissionRevenue: "Commission revenue Y1",
        netIncome: "Net income Y1",
        cashMonth: "Positive cash month",
        asp: "ASP",
        capture: "Capture",
        closeAndCpl: "Close / CPL",
        salaries: "Payroll Y1",
      },
      metricsGlossary: [
        "GMV: Gross merchandise value",
        "CPL: Cost per lead",
        "ASP: Average selling price",
      ],
      glossaryTitle: "Glossary",
      glossaryItems: [
        "GMV: Value of transacted properties",
        "Capture: Commission kept by TAO",
        "ASP: Average property price",
      ],
      howToReadTitle: "How to read",
      howToReadPoints: [
        "Adjust the controls to recalculate the model.",
        "Tables reflect the results with the current assumptions.",
        "Use Reset to restore the defaults.",
      ],
      howToReadDisclaimer: "Amounts in USD.",
      controlsTitle: "Controls",
      controlsRealtimeNote: "Changes update the model instantly.",
      resetButton: "Reset",
      controlGroups: {
        commercial: {
          title: "Commercial assumptions",
          aspLabel: "ASP (USD)",
          aspHelp: "Average selling price per closing.",
          captureLabel: "% Capture",
          captureHelp: "Commission percentage retained by TAO.",
          closeRateLabel: "% Close",
          closeRateHelp: "Share of leads that convert to sales.",
          cplLabel: "CPL (USD)",
          cplHelp: "Cost per lead generated.",
          closingsGroupTitle: "Closings / GMV",
          closingLabelY1: "Closings Y1",
          closingLabelY2: "Closings Y2",
          closingLabelY3: "Closings Y3",
          closingHelpY1: "Estimated GMV Y1: {gmv} with current ASP.",
          closingHelpY2: "Estimated GMV Y2: {gmv} with current ASP.",
          closingHelpY3: "Estimated GMV Y3: {gmv} with current ASP.",
        },
        team: {
          title: "Team",
          intro: "Configure salaries and hires by year.",
          srTitle: "AI Sr Analyst",
          jrTitle: "AI Jr Analyst",
          salaryLabel: "Monthly salary (USD)",
          salaryHelpSr: "Senior analyst salaries across hiring waves.",
          salaryHelpJr: "Junior analyst salaries across hiring waves.",
          countLabel: "Hires",
          srCountHelp: "Number of senior hires spread over years.",
          jrCountHelp: "Number of junior hires spread over years.",
          yearLabel: "Year",
        },
        brainium: {
          title: "Brainium",
          monthlyLabel: "Brainium monthly fee ({months} months)",
          monthlyHelp: "Fixed monthly fee during the initial months.",
          successLabel: "Success fee",
          successHelp: "Payment triggered on success.",
          revshareLabel: "% Revshare",
          revshareHelp: "Revenue share percentage.",
          totalsHelp: "Total per year: Y1 {y1}, Y2 {y2}, Y3 {y3}.",
        },
      },
      sectionTitles: {
        teamDashboard: "Team dashboard",
        unitEconomics: "Unit economics",
        pnl: "P&L",
        sensitivity: "Sensitivity",
        cash: "Cash",
      },
      teamTableHeaders: ["Role", "Monthly salary", "Start"],
      teamTableEmpty: "Add hires to see yearly costs.",
      unitEconomicsRows: {
        commission: "Commission per closing",
        acquisition: "Acquisition per closing",
        contribution: "Contribution per closing",
      },
      pnlHeaders: [
        "Year",
        "Closings",
        "GMV",
        "Leads",
        "Media",
        "Commission revenue",
        "% Broker",
        "Payroll",
        "Overhead",
        "Net income",
        "Net margin",
      ],
      sensitivityHeaders: [
        "Scenario",
        "Closings",
        "% Capture",
        "% Close / CPL",
        "GMV",
        "Leads / Media",
        "Commission revenue",
        "% Broker",
        "Payroll + OH",
        "Net income",
        "Net margin",
      ],
      cashChartTitle: "Cash flow Y1",
      cashSummaryTitle: "Cash summary",
      cashSummary: {
        burn: "Monthly burn pre-sales:",
        net: "Monthly net income post-sales:",
        deficit: "Max deficit:",
        turn: "Month turns positive:",
      },
    },
    investorNarrativeView: {
      title: 'Investment narrative',
      intro: 'Explanation of TAO’s investment model.',
    },
  },
} as const;
