import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  wrap: {
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial",
    color: "#111827",
    lineHeight: 1.45,
    padding: "24px",
    background: "#f9fafb",
  },
  header: {
    marginBottom: 16,
  },
  h1: {
    fontSize: 24,
    margin: 0,
    fontWeight: 700,
  },
  headStats: {
    marginTop: 12,
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  },
  headNote: {
    marginTop: 8,
    fontSize: 13,
    color: "#4b5563",
    maxWidth: 900,
  },
  section: {
    margin: "16px 0 24px",
  },
  h2: {
    fontSize: 18,
    margin: "0 0 12px",
    fontWeight: 700,
    color: "#111827",
  },
  h3: {
    fontSize: 14,
    margin: "0 0 8px",
    fontWeight: 700,
    color: "#1f2937",
  },
  p: {
    margin: 0,
    fontSize: 14,
  },
  pSmall: {
    margin: 0,
    fontSize: 13,
  },
  ul: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 13,
  },
  ol: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 14,
  },
  grid2: {
    display: "grid",
    gap: 16,
    gridTemplateColumns: "1fr 1fr",
  },
  grid3: {
    display: "grid",
    gap: 16,
    gridTemplateColumns: "repeat(3, 1fr)",
  },
  agentCard: {
    background: "linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)",
    border: "1px solid #e5e7eb",
    boxShadow: "0 6px 16px rgba(0,0,0,0.04)",
  },
  agentPill: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 10px",
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0.2,
    background: "#e0f2fe",
    color: "#075985",
    marginBottom: 6,
  },
  agentTitle: {
    fontSize: 15,
    margin: "0 0 6px",
    fontWeight: 700,
    color: "#0f172a",
  },
  agentText: {
    margin: "0 0 8px",
    fontSize: 13,
    color: "#334155",
  },
  card: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: 16,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
  },
  flowGrid: {
    display: "grid",
    gap: 16,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  },
  flowStep: {
    borderRadius: 14,
    border: "1px solid #e5e7eb",
    padding: "14px 14px 16px",
    background: "#ffffff",
    boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  stepBadge: {
    width: 24,
    height: 24,
    borderRadius: 999,
    background: "#2563eb",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 600,
    marginBottom: 4,
  },
  flowTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "#111827",
  },
  keystat: {
    display: "flex",
    flexDirection: "column",
    padding: "10px 12px",
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    minWidth: 160,
  },
  keystatValue: {
    fontSize: 16,
    fontWeight: 700,
  },
  keystatLabel: {
    fontSize: 13,
    color: "#6b7280",
  },
  table: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
    fontSize: 13,
    minWidth: 640,
  },
  languageToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    padding: 2,
    borderRadius: 999,
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
  },
  languageButton: {
    padding: "4px 8px",
    borderRadius: 999,
    border: "none",
    background: "transparent",
    fontSize: 13,
    fontWeight: 600,
    color: "#4b5563",
    cursor: "pointer",
    lineHeight: 1.2,
  },
  languageButtonActive: {
    color: "#1d4ed8",
    background: "#eff6ff",
    fontWeight: 700,
    textDecoration: "underline",
  },
  th: {
    textAlign: "left",
    padding: "8px 10px",
    borderBottom: "1px solid #e5e7eb",
    background: "#f3f4f6",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "8px 10px",
    borderBottom: "1px solid #f3f4f6",
    whiteSpace: "nowrap",
  },
  svg: {
    display: "block",
  },
  controlsHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
  },
  resetButton: {
    fontSize: 12,
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid #d1d5db",
    background: "#ffffff",
    cursor: "pointer",
  },
  controlsGrid: {
    display: "grid",
    gap: 16,
  },
  controlGroup: {
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: 12,
    background: "#ffffff",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  controlLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "#111827",
    marginBottom: 4,
  },
  controlField: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginTop: 4,
  },
  controlFieldLabel: {
    fontSize: 13,
    color: "#4b5563",
  },
  controlInput: {
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid #d1d5db",
    fontSize: 13,
  },
  controlHelp: {
    fontSize: 13,
    color: "#6b7280",
    marginTop: 2,
  },
  teamGrid: {
    display: "grid",
    gap: 10,
  },
  teamMemberCard: {
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    padding: 10,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    background: "#f9fafb",
  },
  teamMemberHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  teamToggleLabel: {
    fontSize: 13,
    color: "#111827",
    display: "flex",
    alignItems: "center",
  },
  teamFieldsGrid: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
  },
  exampleCard: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 16,
    boxShadow: "0 8px 20px rgba(0,0,0,0.04)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  exampleStep: {
    alignSelf: "flex-start",
    padding: "4px 10px",
    borderRadius: 999,
    background: "#eef2ff",
    color: "#4338ca",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0.3,
  },
};
